# Generated by Django 4.2.27 on 2026-01-09 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('plug_type', models.CharField(choices=[('type2', 'Type2'), ('ccs', 'CCS'), ('chademo', 'CHAdeMO')], default='type2', max_length=20)),
                ('price_per_kwh', models.DecimalField(decimal_places=2, default=0.3, max_digits=6)),
                ('rating', models.FloatField(default=5.0)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('free', 'Free'), ('booked', 'Booked'), ('occupied', 'Occupied')], default='free', max_length=10)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
